### ISSUE TITLE
Bloodmoons do not start when multiverse is installed

### ISSUE THREAD

**Issue by Cinder4198** [refractored/bloodmoon#6]
I installed the plugin onto my server and ran /bloodmoon start, but doing so only prints the warning message, then outputs this error.
```[23:46:05 WARN]: [Bloodmoon] Task #37 for Bloodmoon v0.8.2 generated an exception
java.lang.NullPointerException: Cannot invoke "net.refractored.bloodmoon.managers.PeriodicManager.close()" because "this.actuatorPeriodic" is null
        at net.refractored.bloodmoon.managers.BloodmoonManager.StopBloodMoon(BloodmoonManager.java:190) ~[bloodmoon.jar:?]
        at net.refractored.bloodmoon.PeriodicNightCheck.CheckDay(PeriodicNightCheck.java:136) ~[bloodmoon.jar:?]
        at net.refractored.bloodmoon.PeriodicNightCheck.run(PeriodicNightCheck.java:79) ~[bloodmoon.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

After a bit of experimenting, it seemed like it only occurs when the multiverse core plugin is installed.

**Comment by gel6ter** [comment]
looking for a solution as well

**Comment by refractored** [comment]
As a workaround until the i recode the plugin you can use this as a world manager:
https://www.spigotmc.org/resources/myworlds.39594/
