### ISSUE TITLE
Support for eco 6.70.0 on Paper 1.20.6

### ISSUE THREAD

**Issue by HaHaWTH** [refractored/bloodmoon#7]
Bloodmoon is an awesome plugin, but when I tried to run it on Paper 1.20.6 with eco 6.70.0.
I encountered some problems:

This seems only happen when bloodmoon starts.

**Stacktraces**

```
[10:07:14 WARN]: [Bloodmoon] Task #5884 for Bloodmoon v0.8.2 generated an exception
java.lang.NullPointerException: Cannot invoke "net.refractored.bloodmoon.managers.PeriodicManager.close()" because "this.actuatorPeriodic" is null
        at bloodmoon.jar/net.refractored.bloodmoon.managers.BloodmoonManager.StopBloodMoon(BloodmoonManager.java:190) ~[bloodmoon.jar:?]
        at bloodmoon.jar/net.refractored.bloodmoon.PeriodicNightCheck.CheckDay(PeriodicNightCheck.java:131) ~[bloodmoon.jar:?]
        at bloodmoon.jar/net.refractored.bloodmoon.PeriodicNightCheck.run(PeriodicNightCheck.java:74) ~[bloodmoon.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:91) ~[leaf-1.20.6.jar:git-Leaf-"38e9d59"]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:481) ~[leaf-1.20.6.jar:git-Leaf-"38e9d59"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1707) ~[leaf-1.20.6.jar:git-Leaf-"38e9d59"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:515) ~[leaf-1.20.6.jar:git-Leaf-"38e9d59"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1589) ~[leaf-1.20.6.jar:git-Leaf-"38e9d59"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[leaf-1.20.6.jar:git-Leaf-"38e9d59"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[leaf-1.20.6.jar:git-Leaf-"38e9d59"]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by refractored** [comment]
Im going to recode this whole plugin soon cause the original authors source code is tooo messy for me to deal with :p

**Comment by Raidware** [comment]
> Im going to recode this whole plugin soon cause the original authors source code is tooo messy for me to deal with :p

any ETA?

**Comment by casperwtf** [comment]
```
[15:10:10 WARN]: [Bloodmoon] Task #3302 for Bloodmoon v0.8.2 generated an exception
java.lang.NullPointerException: Cannot invoke "net.refractored.bloodmoon.managers.PeriodicManager.close()" because "this.actuatorPeriodic" is null
        at bloodmoon.jar/net.refractored.bloodmoon.managers.BloodmoonManager.StopBloodMoon(BloodmoonManager.java:190) ~[bloodmoon.jar:?]
        at bloodmoon.jar/net.refractored.bloodmoon.PeriodicNightCheck.CheckDay(PeriodicNightCheck.java:136) ~[bloodmoon.jar:?]
        at bloodmoon.jar/net.refractored.bloodmoon.PeriodicNightCheck.run(PeriodicNightCheck.java:79) ~[bloodmoon.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-57-b483da4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
