### ISSUE TITLE
Bloodmoons fail to start, even with the start command

### ISSUE THREAD

**Issue by BorealPawPads** [refractored/bloodmoon#8]
I'm not sure how or what happened, but several times now the message "The Sky is darker than usual tonight" appears, but a blood moon event fails to start. No "boss bar" appears, and drops are not dropping.

No sound effects play, no errors appear in the console, and the only sound that does play is the one that plays when the blood moon ends.

**Comment by BorealPawPads** [comment]
Update, this message appeared as I was typing out the bug report.

`
[12:34:19 WARN]: [Bloodmoon] Task #4114575 for Bloodmoon v0.8.2 generated an exception
java.lang.NullPointerException: Cannot invoke "net.refractored.bloodmoon.managers.PeriodicManager.close()" because "this.actuatorPeriodic" is null
        at net.refractored.bloodmoon.managers.BloodmoonManager.StopBloodMoon(BloodmoonManager.java:190) ~[bloodmoon.jar:?]
        at net.refractored.bloodmoon.PeriodicNightCheck.CheckDay(PeriodicNightCheck.java:136) ~[bloodmoon.jar:?]
        at net.refractored.bloodmoon.PeriodicNightCheck.run(PeriodicNightCheck.java:79) ~[bloodmoon.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

`

**Comment by BorealPawPads** [comment]
Okay, after further testing it was caused by installing "DynaTech", an addon for another Spigot plugin. I wonder if this is related to DynaTech creating a fourth dimension called "dimensionalhome".

In my testing, it seems that the blood moon does not even *start* or is instantly stopped.

So this is basically "resolved".

**Comment by refractored** [comment]
> Okay, after further testing it was caused by installing "DynaTech", an addon for another Spigot plugin. I wonder if this is related to DynaTech creating a fourth dimension called "dimensionalhome".
> 
> In my testing, it seems that the blood moon does not even _start_ or is instantly stopped.
> 
> So this is basically "resolved".

This is the reason why im currently recoding the plugin, I highly recommend switching over after its release, as the plugins will be very similar (from the server owners perspective)
